
export const GETDATA_REQUEST = "GETDATA_REQUEST";
export const GETDATA_SUCCESS = "GETDATA_SUCCESS";
export const GETDATA_FAILURE = "GETDATA_FAILURE";

export const DELETE_REQUEST = "DELETE_REQUEST";
export const DELETE_SUCCESS = "DELETE_SUCCESS";
export const DELETE_FAILURE = "DELETE_FAILURE";

export const DELCUSTOMER_REQUEST = "DELCUSTOMER_REQUEST";
export const DELCUSTOMER_SUCCESS = "DELCUSTOMER_SUCCESS";
export const DELCUSTOMER_FAILURE = "DELCUSTOMER_FAILURE";

export const EDITCUSTOMER_REQUEST = "EDITCUSTOMER_REQUEST";
export const EDITCUSTOMER_SUCCESS = "EDITCUSTOMER_SUCCESS";
export const EDITCUSTOMER_FAILURE = "EDITCUSTOMER_FAILURE";


export const CUSTOMER_REQUEST = "CUSTOMER_REQUEST";
export const CUSTOMER_SUCCESS = "CUSTOMER_SUCCESS";
export const CUSTOMER_FAILURE = "CUSTOMER_FAILURE";


export const ORDER_SUCCESS = "ORDER_SUCCESS";
export const GETADMINDATA_SUCCESS = "GETADMINDATA_SUCCESS";
export const GETADMINDATA_REQUEST = "GETADMINDATA_REQUEST";
export const GETADMINDATA_FAILURE = "GETADMINDATA_FAILURE";


export const POSTDATA_REQUEST = "POSTDATA_REQUEST";
export const POSTDATA_SUCCESS = "POSTDATA_SUCCESS";
export const POSTDATA_FAILURE = "POSTDATA_FAILURE";
export const  GETACCESSORIES_SUCCESS= "GETACCESSORIES_SUCCESS";


export const GETSINGLEPRODUCT_REQUEST = "GETSINGLEPRODUCT_REQUEST";
export const GETSINGLEPRODUCT_SUCCESS = "GETSINGLEPRODUCT_SUCCESS";
export const GETSINGLEPRODUCT_FAILURE = "GETSINGLEPRODUCT_FAILURE";

export const GETACCESSORYSINGLEPRODUCT_SUCCESS = "GETACCESSORYSINGLEPRODUCT_SUCCESS";


export const EDITPRODUCT_SUCCESS = "EDITPRODUCT_SUCCESS";