
export const GETDATA_REQUEST = "GETDATA_REQUEST";
export const GETDATA_SUCCESS = "GETDATA_SUCCESS";
export const GETDATA_FAILURE = "GETDATA_FAILURE";

export const DELETE_REQUEST = "DELETE_REQUEST";
export const DELETE_SUCCESS = "DELETE_SUCCESS";
export const DELETE_FAILURE = "DELETE_FAILURE";

export const POSTDATA_REQUEST = "POSTDATA_REQUEST";
export const POSTDATA_SUCCESS = "POSTDATA_SUCCESS";
export const POSTDATA_FAILURE = "POSTDATA_FAILURE";
export const  GETACCESSORIES_SUCCESS= "GETACCESSORIES_SUCCESS";


export const GETSINGLEPRODUCT_REQUEST = "GETSINGLEPRODUCT_REQUEST";
export const GETSINGLEPRODUCT_SUCCESS = "GETSINGLEPRODUCT_SUCCESS";
export const GETSINGLEPRODUCT_FAILURE = "GETSINGLEPRODUCT_FAILURE";

export const GETACCESSORYSINGLEPRODUCT_SUCCESS = "GETACCESSORYSINGLEPRODUCT_SUCCESS";


export const EDITPRODUCT_SUCCESS = "EDITPRODUCT_SUCCESS";