
export const GETSINGLEPRODUCT_REQUEST = "GETSINGLEPRODUCT_REQUEST";
export const GETSINGLEPRODUCT_SUCCESS = "GETSINGLEPRODUCT_SUCCESS";
export const GETSINGLEPRODUCT_FAILURE = "GETSINGLEPRODUCT_FAILURE";